#include <Arduino.h>
#include <WiFi.h>
#include <WebServer.h>
#include <Preferences.h>
#include <ArduinoOTA.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#if __has_include("secrets.h")
#include "secrets.h"
#else
#include "secrets.example.h"
#endif
#include "ui.h"

#ifndef WIFI_SSID
#define WIFI_SSID ""
#endif
#ifndef WIFI_PASSWORD
#define WIFI_PASSWORD ""
#endif
#ifndef AP_SSID
#define AP_SSID "SprinklerController"
#endif
#ifndef AP_PASSWORD
#define AP_PASSWORD "ChangeMe123"
#endif
#ifndef OTA_PASSWORD
#define OTA_PASSWORD "change-this-unique-ota-password"
#endif

namespace Cfg {
constexpr uint8_t DIR_PIN=25, PWM_PIN=26, PRESSURE_PIN=34, DIR_OPEN_LEVEL=HIGH, ADC_SAMPLES=16, ZERO_SAMPLES=60;
constexpr float SENSOR_MIN_V=.5f,SENSOR_MAX_V=4.5f,SENSOR_FS_PSI=150.f,DIVIDER_RATIO=2.f/3.f,PRESSURE_GAIN=1.f;
constexpr float SENSOR_FAULT_LOW_V=.20f,SENSOR_FAULT_HIGH_V=4.80f,MAX_ZERO_OFFSET_PSI=30.f,MAX_SETPOINT_PSI=100.f,HARD_MAX_PRESSURE_PSI=120.f,OVERPRESSURE_CLEAR_PSI=115.f;
constexpr uint32_t MIN_PULSE_MS=20,MAX_PULSE_MS=1000,MIN_TRAVEL_MS=100,MAX_TRAVEL_MS=120000,MAX_OVERTRAVEL_MS=1000;
}
struct TuningConfig {
  float filterAlpha=.10f,deadbandPsi=.75f,error1Psi=1.5f,error2Psi=3.f,error3Psi=6.f;
  uint32_t controlIntervalMs=100,settleMs=400,pulse1Ms=70,pulse2Ms=110,pulse3Ms=200,pulse4Ms=325;
  uint32_t openTravelMs=4500,closeTravelMs=4500,openOvertravelMs=0,closeOvertravelMs=0;
};
WebServer server(80); Preferences prefs; TuningConfig tuning;
enum class Mode:uint8_t{MANUAL,AUTO}; enum class Motion:uint8_t{STOPPED,OPENING,CLOSING}; enum class Fault:uint8_t{NONE,SENSOR,OVERPRESSURE}; enum class RefDir:uint8_t{NONE,OPEN,CLOSE};
Mode mode=Mode::MANUAL; Motion motion=Motion::STOPPED; Fault fault=Fault::NONE; RefDir refDir=RefDir::NONE;
float targetPsi=20.f,adcMv=0,adcV=0,sensorV=0,rawPsi=0,filteredPsi=NAN,pressureOffsetPsi=0,zeroClampPsi=.5f,estimatedPosition=0;
float zeroSamples[Cfg::ZERO_SAMPLES]{}; uint8_t zeroCount=0,goodSamples=0; uint32_t zeroStart=0,pulseStart=0,pulseEnd=0,settleUntil=0,lastRead=0,lastControl=0,referenceUsed=0;
bool sensorValid=false,pressureReady=false,stationConnected=false,zeroActive=false,positionKnown=false,pulseOpen=false;
String lastAction="boot_safe",lastError="",zeroError="",stationSsid="",stationPassword="",wifiError="",wifiState="idle",pendingSsid="",pendingPassword="",previousSsid="",previousPassword="";
bool wifiChangePending=false,wifiRollback=false,wifiSwitchScheduled=false; uint32_t wifiAttemptStart=0,wifiSwitchAt=0;

bool due(uint32_t now,uint32_t deadline){return int32_t(now-deadline)>=0;}
const char* modeName(){return mode==Mode::AUTO?"auto":"manual";} const char* motionName(){return motion==Motion::STOPPED?"stopped":motion==Motion::OPENING?"opening":"closing";}
const char* faultName(){return fault==Fault::NONE?"none":fault==Fault::SENSOR?"sensor":"overpressure";}
String jsonEscape(const String& s){String o;for(size_t i=0;i<s.length();++i){char c=s[i];if(c=='"'||c=='\\')o+='\\';if((uint8_t)c>=32)o+=c;}return o;}
void logEvent(const char* what){Serial.printf("[%lu] %s pressure=%.2f raw=%.2f target=%.2f mode=%s valve=%s fault=%s\n",(unsigned long)millis(),what,pressureReady?filteredPsi:NAN,rawPsi,targetPsi,modeName(),motionName(),faultName());}
void updatePosition(uint32_t elapsed){if(!positionKnown)return;uint32_t travel=pulseOpen?tuning.openTravelMs:tuning.closeTravelMs;float delta=100.f*elapsed/travel;estimatedPosition=constrain(estimatedPosition+(pulseOpen?delta:-delta),0.f,100.f);}
void stopValve(const char* why){digitalWrite(Cfg::PWM_PIN,LOW);if(motion!=Motion::STOPPED){uint32_t now=millis(),elapsed=now-pulseStart;updatePosition(elapsed);if(refDir!=RefDir::NONE&&((refDir==RefDir::OPEN)==pulseOpen))referenceUsed+=elapsed;motion=Motion::STOPPED;settleUntil=now+tuning.settleMs;lastAction=why;logEvent(why);}}
bool startPulse(bool open,uint32_t ms,const char* origin){uint32_t now=millis();if(motion!=Motion::STOPPED||!due(now,settleUntil))return false;ms=constrain(ms,Cfg::MIN_PULSE_MS,Cfg::MAX_PULSE_MS);
  if(origin[0]=='a'&&!positionKnown)return false;
  if(origin[0]=='m'||origin[0]=='a'){
    if(refDir!=RefDir::NONE){uint32_t limit=(refDir==RefDir::OPEN?tuning.openTravelMs+tuning.openOvertravelMs:tuning.closeTravelMs+tuning.closeOvertravelMs);if((refDir==RefDir::OPEN)!=open||referenceUsed+ms>limit)return false;}
    else{if(!positionKnown)return false;float travel=open?tuning.openTravelMs*(100.f-estimatedPosition)/100.f:tuning.closeTravelMs*estimatedPosition/100.f;uint32_t extra=open?tuning.openOvertravelMs:tuning.closeOvertravelMs;if(ms>travel+extra)return false;}
  }
  digitalWrite(Cfg::PWM_PIN,LOW);digitalWrite(Cfg::DIR_PIN,open?Cfg::DIR_OPEN_LEVEL:!Cfg::DIR_OPEN_LEVEL);delayMicroseconds(20);digitalWrite(Cfg::PWM_PIN,HIGH);pulseStart=now;pulseEnd=now+ms;pulseOpen=open;motion=open?Motion::OPENING:Motion::CLOSING;lastAction=String(origin)+(open?"_open_":"_close_")+String(ms)+"ms";return true;}
void servicePulse(){if(motion!=Motion::STOPPED&&due(millis(),pulseEnd))stopValve("pulse_complete");}
void updatePressure(){uint32_t now=millis();if(now-lastRead<50)return;lastRead=now;uint32_t total=0;for(uint8_t i=0;i<Cfg::ADC_SAMPLES;i++){total+=analogReadMilliVolts(Cfg::PRESSURE_PIN);delayMicroseconds(100);}adcMv=(float)total/Cfg::ADC_SAMPLES;adcV=adcMv/1000.f;sensorV=adcV/Cfg::DIVIDER_RATIO;rawPsi=(sensorV-Cfg::SENSOR_MIN_V)/(Cfg::SENSOR_MAX_V-Cfg::SENSOR_MIN_V)*Cfg::SENSOR_FS_PSI;sensorValid=isfinite(sensorV)&&sensorV>=Cfg::SENSOR_FAULT_LOW_V&&sensorV<=Cfg::SENSOR_FAULT_HIGH_V;
  if(!sensorValid){goodSamples=0;fault=Fault::SENSOR;mode=Mode::MANUAL;zeroActive=false;zeroError="Sensor invalid during capture";stopValve("sensor_fault_stop");lastError="Pressure sensor outside 0.20–4.80 V";return;}
  if(goodSamples<5)++goodSamples;if(goodSamples>=5&&fault==Fault::SENSOR){fault=Fault::NONE;lastError="";pressureReady=false;}
  float calibrated=rawPsi*Cfg::PRESSURE_GAIN+pressureOffsetPsi;if(!pressureReady){filteredPsi=calibrated;pressureReady=true;}else filteredPsi=tuning.filterAlpha*calibrated+(1.f-tuning.filterAlpha)*filteredPsi;if(fabsf(filteredPsi)<=zeroClampPsi)filteredPsi=0.f;
  if(zeroActive){if(mode!=Mode::MANUAL||motion!=Motion::STOPPED||!due(millis(),settleUntil)||!sensorValid){zeroActive=false;zeroError="Capture canceled: controller state changed";}else if(zeroCount<Cfg::ZERO_SAMPLES)zeroSamples[zeroCount++]=rawPsi;
    if(zeroActive&&zeroCount>=Cfg::ZERO_SAMPLES&&millis()-zeroStart>=3000){float sorted[Cfg::ZERO_SAMPLES];memcpy(sorted,zeroSamples,sizeof(sorted));for(uint8_t i=1;i<Cfg::ZERO_SAMPLES;i++){float v=sorted[i];int j=i-1;while(j>=0&&sorted[j]>v){sorted[j+1]=sorted[j];--j;}sorted[j+1]=v;}float med=(sorted[29]+sorted[30])*.5f,spread=sorted[53]-sorted[6],off=-med*Cfg::PRESSURE_GAIN;
      if(spread>1.f)zeroError="Capture rejected: samples were unstable";else if(!isfinite(off)||fabsf(off)>Cfg::MAX_ZERO_OFFSET_PSI)zeroError="Capture rejected: correction exceeds 30 PSI";else if(prefs.putFloat("zero_offset",off)!=sizeof(float))zeroError="Capture failed: could not save offset";else{pressureOffsetPsi=off;filteredPsi=0;pressureReady=true;lastAction="zero_calibrated";zeroError="Zero saved from stable 3-second capture";logEvent("zero_calibrated");}zeroActive=false;}}
}
uint32_t pulseFor(float e){if(e<=tuning.error1Psi)return tuning.pulse1Ms;if(e<=tuning.error2Psi)return tuning.pulse2Ms;if(e<=tuning.error3Psi)return tuning.pulse3Ms;return tuning.pulse4Ms;}
void serviceControl(){if(!sensorValid||!pressureReady||motion!=Motion::STOPPED||!due(millis(),settleUntil)||millis()-lastControl<tuning.controlIntervalMs)return;lastControl=millis();if(filteredPsi>Cfg::HARD_MAX_PRESSURE_PSI){fault=Fault::OVERPRESSURE;startPulse(false,300,"safety");return;}if(fault==Fault::OVERPRESSURE){if(filteredPsi<Cfg::OVERPRESSURE_CLEAR_PSI)fault=Fault::NONE;else{startPulse(false,250,"safety");return;}}if(mode!=Mode::AUTO||!positionKnown)return;float err=targetPsi-filteredPsi;if(fabsf(err)<=tuning.deadbandPsi)return;float scale=fabsf(err)<=tuning.error1Psi?.65f:1.f;startPulse(err>0,max((uint32_t)Cfg::MIN_PULSE_MS,(uint32_t)(pulseFor(fabsf(err))*scale)),"auto");}
bool badOrigin(){if(!server.hasHeader("Origin"))return false;String o=server.header("Origin"),h="http://"+server.hostHeader();return o!=h;}
void sendError(int code,const char* message){server.send(code,"application/json",String("{\"ok\":false,\"error\":\"")+message+"\"}");}
bool argFloat(const char* key,float& out){if(!server.hasArg(key))return false;String s=server.arg(key);s.trim();if(!s.length()||s.length()>24)return false;char* e=nullptr;out=strtof(s.c_str(),&e);return e!=s.c_str()&&*e=='\0'&&isfinite(out);}
bool argUInt(const char* key,uint32_t& out){float f;if(!argFloat(key,f)||f<0||f>120000||floorf(f)!=f)return false;out=(uint32_t)f;return true;}
void status(){char pressure[24];if(pressureReady)snprintf(pressure,sizeof(pressure),"%.2f",filteredPsi);else strcpy(pressure,"null");String ip=stationConnected?WiFi.localIP().toString():WiFi.softAPIP().toString();char out[1700];snprintf(out,sizeof(out),"{\"pressure\":%s,\"rawPressure\":%.3f,\"pressureOffsetPsi\":%.3f,\"filterAlpha\":%.3f,\"zeroClampPsi\":%.2f,\"target\":%.2f,\"adcMillivolts\":%.1f,\"adcVoltage\":%.4f,\"sensorVoltage\":%.4f,\"mode\":\"%s\",\"valve\":\"%s\",\"fault\":\"%s\",\"system\":\"%s\",\"wifiRssi\":%d,\"wifi\":\"%s\",\"ip\":\"%s\",\"uptimeMs\":%lu,\"lastAction\":\"%s\",\"lastError\":\"%s\",\"valvePosition\":%.1f,\"positionKnown\":%s,\"referenceActive\":%s,\"referenceDirection\":\"%s\",\"referencePulseUsedMs\":%lu,\"referencePulseBudgetMs\":%lu,\"zeroCaptureActive\":%s,\"zeroCaptureSamples\":%u,\"zeroCaptureProgress\":%u,\"zeroCaptureError\":\"%s\",\"warning\":\"Throttling is not a static pressure regulator; install rated mechanical relief hardware.\"}",pressure,rawPsi,pressureOffsetPsi,tuning.filterAlpha,zeroClampPsi,targetPsi,adcMv,adcV,sensorV,modeName(),motionName(),faultName(),fault==Fault::NONE?(sensorValid?"ok":"sensor_fault"):faultName(),stationConnected?WiFi.RSSI():0,stationConnected?"station+ap":"access_point",ip.c_str(),(unsigned long)millis(),lastAction.c_str(),lastError.c_str(),estimatedPosition,positionKnown?"true":"false",refDir!=RefDir::NONE?"true":"false",refDir==RefDir::OPEN?"open":refDir==RefDir::CLOSE?"close":"none",(unsigned long)referenceUsed,(unsigned long)(refDir==RefDir::OPEN?tuning.openTravelMs+tuning.openOvertravelMs:refDir==RefDir::CLOSE?tuning.closeTravelMs+tuning.closeOvertravelMs:0),zeroActive?"true":"false",zeroCount,(unsigned)(zeroCount*100/Cfg::ZERO_SAMPLES),zeroError.c_str());server.send(200,"application/json",out);}
void getConfig(){char out[920];snprintf(out,sizeof(out),"{\"filterAlpha\":%.3f,\"zeroClampPsi\":%.2f,\"deadbandPsi\":%.3f,\"controlIntervalMs\":%lu,\"settleMs\":%lu,\"error1Psi\":%.3f,\"error2Psi\":%.3f,\"error3Psi\":%.3f,\"pulse1Ms\":%lu,\"pulse2Ms\":%lu,\"pulse3Ms\":%lu,\"pulse4Ms\":%lu,\"openTravelMs\":%lu,\"closeTravelMs\":%lu,\"openOvertravelMs\":%lu,\"closeOvertravelMs\":%lu}",tuning.filterAlpha,zeroClampPsi,tuning.deadbandPsi,(unsigned long)tuning.controlIntervalMs,(unsigned long)tuning.settleMs,tuning.error1Psi,tuning.error2Psi,tuning.error3Psi,(unsigned long)tuning.pulse1Ms,(unsigned long)tuning.pulse2Ms,(unsigned long)tuning.pulse3Ms,(unsigned long)tuning.pulse4Ms,(unsigned long)tuning.openTravelMs,(unsigned long)tuning.closeTravelMs,(unsigned long)tuning.openOvertravelMs,(unsigned long)tuning.closeOvertravelMs);server.send(200,"application/json",out);}
void saveConfig(){if(badOrigin())return sendError(403,"Cross-origin request rejected");TuningConfig c; c=tuning;float newZeroClamp=zeroClampPsi;if(!argFloat("zeroClampPsi",newZeroClamp))return sendError(400,"Missing or invalid zeroClampPsi");uint32_t* ints[]={&c.controlIntervalMs,&c.settleMs,&c.pulse1Ms,&c.pulse2Ms,&c.pulse3Ms,&c.pulse4Ms,&c.openTravelMs,&c.closeTravelMs,&c.openOvertravelMs,&c.closeOvertravelMs};const char* ik[]={"controlIntervalMs","settleMs","pulse1Ms","pulse2Ms","pulse3Ms","pulse4Ms","openTravelMs","closeTravelMs","openOvertravelMs","closeOvertravelMs"};float* fs[]={&c.filterAlpha,&c.deadbandPsi,&c.error1Psi,&c.error2Psi,&c.error3Psi};const char* fk[]={"filterAlpha","deadbandPsi","error1Psi","error2Psi","error3Psi"};for(int i=0;i<10;i++)if(!argUInt(ik[i],*ints[i]))return sendError(400,"Missing or invalid integer config field");for(int i=0;i<5;i++)if(!argFloat(fk[i],*fs[i]))return sendError(400,"Missing or invalid numeric config field");
  if(c.filterAlpha<.01f||c.filterAlpha>1||c.deadbandPsi<.05f||c.deadbandPsi>20||c.controlIntervalMs<50||c.controlIntervalMs>5000||c.settleMs>10000||c.error1Psi<=0||c.error2Psi<=c.error1Psi||c.error3Psi<=c.error2Psi||c.pulse1Ms<20||c.pulse1Ms>1000||c.pulse2Ms<20||c.pulse2Ms>1000||c.pulse3Ms<20||c.pulse3Ms>1000||c.pulse4Ms<20||c.pulse4Ms>1000||c.openTravelMs<Cfg::MIN_TRAVEL_MS||c.closeTravelMs<Cfg::MIN_TRAVEL_MS||c.openTravelMs>Cfg::MAX_TRAVEL_MS||c.closeTravelMs>Cfg::MAX_TRAVEL_MS||c.openOvertravelMs>Cfg::MAX_OVERTRAVEL_MS||c.closeOvertravelMs>Cfg::MAX_OVERTRAVEL_MS)return sendError(400,"Config value outside allowed range");
  if(newZeroClamp<0.f||newZeroClamp>5.f)return sendError(400,"zeroClampPsi must be from 0 to 5 PSI");if(prefs.putBytes("tuning",&c,sizeof(c))!=sizeof(c)||prefs.putFloat("zero_clamp",newZeroClamp)!=sizeof(float))return sendError(500,"Could not persist controller settings");tuning=c;zeroClampPsi=newZeroClamp;server.send(200,"application/json","{\"ok\":true,\"message\":\"Controller settings saved\"}");}
void setpoint(){float v;if(badOrigin())return sendError(403,"Cross-origin request rejected");if(!argFloat("psi",v)||v<0||v>Cfg::MAX_SETPOINT_PSI)return sendError(400,"psi must be 0 to 100");targetPsi=v;prefs.putFloat("target",v);server.send(200,"application/json","{\"ok\":true,\"message\":\"Setpoint saved\"}");}
void automatic(){if(badOrigin())return sendError(403,"Cross-origin request rejected");bool on=server.arg("enabled")=="1";if(!on&&server.arg("enabled")=="0"){mode=Mode::MANUAL;server.send(200,"application/json","{\"ok\":true,\"message\":\"AUTO off\"}");return;}if(!on)return sendError(400,"enabled must be 0 or 1");if(!sensorValid||!pressureReady||fault!=Fault::NONE)return sendError(409,"AUTO blocked until sensor is valid and fault free");if(!positionKnown)return sendError(409,"AUTO blocked until position is referenced");if(motion!=Motion::STOPPED)return sendError(409,"Wait for current pulse to finish");mode=Mode::AUTO;server.send(200,"application/json","{\"ok\":true,\"message\":\"AUTO enabled\"}");}
void pulseApi(){if(badOrigin())return sendError(403,"Cross-origin request rejected");if(mode!=Mode::MANUAL||!sensorValid||fault!=Fault::NONE)return sendError(409,"Manual pulse blocked by controller state");String d=server.arg("direction");bool open=d=="open";if(!open&&d!="close")return sendError(400,"direction must be open or close");uint32_t ms;if(!argUInt("ms",ms)||ms<Cfg::MIN_PULSE_MS||ms>Cfg::MAX_PULSE_MS)return sendError(400,"Pulse must be 20 to 1000 ms");if(!startPulse(open,ms,"manual"))return sendError(409,"Start matching bounded reference first, or wait until stopped and settled");server.send(200,"application/json","{\"ok\":true,\"message\":\"Pulse started\"}");}
void stopApi(){mode=Mode::MANUAL;refDir=RefDir::NONE;zeroActive=false;stopValve("manual_stop");lastAction="manual_stop_auto_off";server.send(200,"application/json","{\"ok\":true,\"message\":\"Stopped; AUTO off\"}");}
void zeroApi(){if(badOrigin())return sendError(403,"Cross-origin request rejected");if(server.arg("confirmed")!="1")return sendError(400,"Explicit confirmation required");if(mode!=Mode::MANUAL||motion!=Motion::STOPPED||!due(millis(),settleUntil)||!sensorValid||fault!=Fault::NONE||!pressureReady)return sendError(409,"Requires valid sensor, MANUAL, stopped and settled");zeroCount=0;zeroError="";zeroStart=millis();zeroActive=true;server.send(202,"application/json","{\"ok\":true,\"message\":\"Capturing fresh samples for 3 seconds\"}");}
void referenceStart(){if(badOrigin())return sendError(403,"Cross-origin request rejected");if(mode!=Mode::MANUAL||motion!=Motion::STOPPED||!due(millis(),settleUntil))return sendError(409,"Reference requires stopped MANUAL mode");String d=server.arg("direction");if(d!="open"&&d!="close")return sendError(400,"direction must be open or close");refDir=d=="open"?RefDir::OPEN:RefDir::CLOSE;referenceUsed=0;positionKnown=false;server.send(200,"application/json","{\"ok\":true,\"message\":\"Bounded manual reference started\"}");}
void referenceMark(){if(badOrigin())return sendError(403,"Cross-origin request rejected");if(server.arg("confirmed")!="1"||refDir==RefDir::NONE||motion!=Motion::STOPPED||!due(millis(),settleUntil))return sendError(409,"Confirm an active stopped reference session");estimatedPosition=refDir==RefDir::OPEN?100.f:0.f;positionKnown=true;refDir=RefDir::NONE;referenceUsed=0;server.send(200,"application/json","{\"ok\":true,\"message\":\"Estimated position reference saved; not a mechanical endstop\"}");}
void wifiGet(){String out="{\"ssid\":\""+jsonEscape(stationSsid)+"\",\"state\":\""+jsonEscape(wifiState)+"\",\"ip\":\""+(stationConnected?WiFi.localIP().toString():String(""))+"\",\"error\":\""+jsonEscape(wifiError)+"\",\"fallbackAp\":\""+WiFi.softAPIP().toString()+"\"}";server.send(200,"application/json",out);}
void wifiPost(){if(badOrigin())return sendError(403,"Cross-origin request rejected");if(wifiChangePending)return sendError(409,"Wi-Fi change already in progress");String ssid=server.arg("ssid"),pass=server.arg("password");if(!ssid.length()||ssid.length()>32||pass.length()>63)return sendError(400,"SSID must be 1–32 chars and password 0–63");previousSsid=stationSsid;previousPassword=stationPassword;pendingSsid=ssid;pendingPassword=pass;wifiChangePending=true;wifiRollback=false;wifiSwitchScheduled=true;wifiSwitchAt=millis()+1000;wifiState="connecting";wifiError="";server.send(202,"application/json","{\"ok\":true,\"message\":\"Wi-Fi connection attempt scheduled; fallback AP remains available\"}");}
void serviceWifi(){if(!wifiChangePending)return;if(wifiSwitchScheduled){if(!due(millis(),wifiSwitchAt))return;wifiSwitchScheduled=false;wifiAttemptStart=millis();WiFi.disconnect(false,false);WiFi.begin(pendingSsid.c_str(),pendingPassword.c_str());return;}if(WiFi.status()==WL_CONNECTED){stationConnected=true;if(!wifiRollback){stationSsid=pendingSsid;stationPassword=pendingPassword;prefs.putString("wifi_ssid",stationSsid);prefs.putString("wifi_pass",stationPassword);wifiState="connected";wifiError="";}else{wifiState="restored_previous";}wifiChangePending=false;pendingPassword="";previousPassword="";logEvent("station_wifi_changed");return;}if(millis()-wifiAttemptStart<15000)return;if(!wifiRollback){wifiRollback=true;wifiState="restoring_previous";wifiError="Could not connect to requested network; restoring previous station";pendingSsid=previousSsid;pendingPassword=previousPassword;wifiAttemptStart=millis();WiFi.disconnect(false,false);if(pendingSsid.length())WiFi.begin(pendingSsid.c_str(),pendingPassword.c_str());else{wifiChangePending=false;stationConnected=false;wifiState="failed_ap_available";pendingPassword="";previousPassword="";}}else{wifiChangePending=false;stationConnected=false;wifiState="failed_ap_available";wifiError="Previous station unavailable; fallback access point remains active";pendingPassword="";previousPassword="";}}
void routes(){const char* h[]={"Origin"};server.collectHeaders(h,1);server.on("/",HTTP_GET,[]{server.send_P(200,"text/html",PAGE);});server.on("/api/status",HTTP_GET,status);server.on("/api/config",HTTP_GET,getConfig);server.on("/api/config",HTTP_POST,saveConfig);server.on("/api/setpoint",HTTP_POST,setpoint);server.on("/api/auto",HTTP_POST,automatic);server.on("/api/pulse",HTTP_POST,pulseApi);server.on("/api/stop",HTTP_POST,stopApi);server.on("/api/zero",HTTP_POST,zeroApi);server.on("/api/reference/start",HTTP_POST,referenceStart);server.on("/api/reference/mark",HTTP_POST,referenceMark);server.on("/api/wifi",HTTP_GET,wifiGet);server.on("/api/wifi",HTTP_POST,wifiPost);server.onNotFound([](){server.send(404,"application/json","{\"ok\":false,\"error\":\"Not found\"}");});}
void network(){WiFi.mode(WIFI_AP_STA);WiFi.setSleep(false);IPAddress ip(192,168,10,1),gw(192,168,10,1),mask(255,255,255,0);WiFi.softAPConfig(ip,gw,mask);WiFi.softAP(AP_SSID,AP_PASSWORD);stationSsid=prefs.getString("wifi_ssid",WIFI_SSID);stationPassword=prefs.getString("wifi_pass",WIFI_PASSWORD);if(stationSsid.length()){WiFi.begin(stationSsid.c_str(),stationPassword.c_str());uint32_t start=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-start<9000){server.handleClient();delay(25);}}stationConnected=WiFi.status()==WL_CONNECTED;wifiState=stationConnected?"connected":"access_point_only";}
void loadConfig(){TuningConfig stored;if(prefs.getBytesLength("tuning")==sizeof(stored)){prefs.getBytes("tuning",&stored,sizeof(stored));tuning=stored;}}
void setupOta(){ArduinoOTA.setHostname("sprinkler-pressure");ArduinoOTA.setPassword(OTA_PASSWORD);ArduinoOTA.onStart([](){mode=Mode::MANUAL;refDir=RefDir::NONE;stopValve("ota_update_stop");Serial.println("Authenticated OTA started; AUTO off.");});ArduinoOTA.begin();}
void setup(){pinMode(Cfg::PWM_PIN,OUTPUT);digitalWrite(Cfg::PWM_PIN,LOW);pinMode(Cfg::DIR_PIN,OUTPUT);digitalWrite(Cfg::DIR_PIN,!Cfg::DIR_OPEN_LEVEL);pinMode(Cfg::PRESSURE_PIN,INPUT);Serial.begin(115200);delay(10);analogReadResolution(12);analogSetPinAttenuation(Cfg::PRESSURE_PIN,ADC_11db);prefs.begin("pressure",false);targetPsi=prefs.getFloat("target",20.f);pressureOffsetPsi=prefs.getFloat("zero_offset",0.f);zeroClampPsi=prefs.getFloat("zero_clamp",.5f);if(!isfinite(zeroClampPsi)||zeroClampPsi<0||zeroClampPsi>5)zeroClampPsi=.5f;loadConfig();if(!isfinite(tuning.filterAlpha)||tuning.filterAlpha<.01f||tuning.filterAlpha>1)tuning=TuningConfig();routes();network();server.begin();setupOta();Serial.printf("Boot safe, AUTO off. AP IP %s\n",WiFi.softAPIP().toString().c_str());}
void loop(){server.handleClient();ArduinoOTA.handle();updatePressure();servicePulse();serviceControl();serviceWifi();stationConnected=WiFi.status()==WL_CONNECTED;}
