#pragma once

const char PAGE[] PROGMEM=R"UI(
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pressure controller</title><style>
:root{color-scheme:dark;--bg:#101820;--panel:#1c2a35;--ink:#edf4f7;--muted:#a9bbc6;--accent:#47c6a5;--warn:#ffbf55;--bad:#ff6868}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:16px system-ui,sans-serif}.wrap{max-width:1050px;margin:auto;padding:16px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.card{background:var(--panel);border-radius:14px;padding:16px;margin:12px 0}.hero{font-size:clamp(2.3rem,8vw,4rem);font-weight:750;line-height:1.1}.label{color:var(--muted);font-size:.82rem;text-transform:uppercase;letter-spacing:.08em}.value{font-size:1.2rem;margin-top:6px}.small{color:var(--muted);font-size:.9rem}.fault{font-weight:800;color:var(--accent)}.fault.bad{color:var(--bad)}.fault.warn{color:var(--warn)}input,select,textarea,button{font:inherit;border:0;border-radius:9px;padding:9px;background:#0e171e;color:var(--ink);border:1px solid #50616c}input[type=number]{width:110px}input[type=password],input[type=text]{width:min(100%,320px)}textarea{width:100%;min-height:74px}button{background:#304550;cursor:pointer;margin:4px 4px 4px 0;border:0}button.primary,button.auto-toggle[aria-pressed=true]{background:#168d76}button.stop{background:#9d343c}button:disabled{opacity:.65;cursor:not-allowed}.row{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin-top:10px}.fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:10px;margin:12px 0}.fields label{display:flex;flex-direction:column;gap:4px;font-size:.85rem;color:var(--muted)}.notice{padding:12px;border-left:4px solid var(--warn);background:#2b2a22;border-radius:6px;margin:12px 0}details summary{cursor:pointer;font-weight:700}canvas{display:block;width:100%;height:190px;background:#0e171e;border-radius:8px;margin:10px 0}progress{width:min(100%,420px);height:18px}pre{white-space:pre-wrap;overflow-wrap:anywhere;color:var(--muted)}.tag{display:inline-block;padding:3px 8px;border-radius:20px;background:#304550;color:var(--muted);font-size:.8rem}.simulation{border:1px solid #47c6a5}h1{margin:6px 0 14px}h2{margin:4px 0 12px;font-size:1.25rem}hr{border:0;border-top:1px solid #40525c;margin:16px 0}
</style></head><body><main class="wrap"><h1>Sprinkler pressure controller</h1><div id="notice" class="notice">AUTO is off until explicitly enabled. Keep it off until commissioning is complete.</div>
<section class="grid"><article class="card"><div class="label">Measured pressure</div><div class="hero"><span id="pressure">--</span> <small>PSI</small></div><div class="small">Raw: <span id="raw-pressure">--</span> PSI · clamp ±<span id="pressure-clamp">0.50</span> PSI</div></article><article class="card"><div class="label">Target pressure</div><div class="value"><span id="target">--</span> PSI</div><div class="row"><input id="setpoint" type="number" min="0" max="100" step="0.1" value="20" aria-label="Target PSI"><button class="primary" onclick="setTarget()">Set target</button></div></article><article class="card"><div class="label">Controller</div><div id="fault" class="value fault">--</div><div class="small">Mode: <span id="mode">--</span> · Valve: <span id="valve">--</span></div><div class="small">Position: <span id="position">unknown</span></div></article></section>
<section class="card"><div class="label">Physical controls</div><div class="row"><button class="auto-toggle" id="auto-toggle" aria-pressed="false" disabled onclick="toggleAuto()">AUTO: CHECKING…</button><button class="stop" onclick="post('/api/stop')">STOP · AUTO OFF</button></div><div class="row"><label>Manual step (ms) <input id="manual-ms" type="number" min="20" max="1000" step="10" value="100"></label><button onclick="manualPulse('open')">OPEN step</button><button onclick="manualPulse('close')">CLOSE step</button></div><div id="message" class="small" role="status"></div><p class="small">Manual pulses require a bounded reference session while position is unknown. These buttons move the physical valve.</p></section>
<section class="card simulation"><h2>Pressure simulator <span class="tag">SIMULATION ONLY · NO HARDWARE COMMANDS</span></h2><p class="small">Water-flow model with a fixed nozzle and adjustable nonlinear valve curve. Defaults are illustrative until measured with water.</p>
<div class="fields"><label>Setpoint (PSI)<input id="sim-target" type="number" min="0" max="120" step="0.5" value="20"></label><label>Supply baseline (PSI)<input id="sim-supply" type="number" min="0" max="150" step="1" value="60"></label><label>Supply profile<select id="sim-profile"><option value="hold">Hold steady</option><option value="step">Step down and recover</option><option value="drop">Step down and stay</option><option value="ramp">Ramp down</option></select></label><label>Supply change (PSI)<input id="sim-step" type="number" min="0" max="150" step="1" value="15"></label><label>Nozzle diameter (mm)<input id="sim-nozzle" type="number" min="0.5" max="100" step="0.1" value="6"></label><label>Full-open valve/nozzle capacity ratio<input id="sim-capacity" type="number" min="0.01" max="100" step="0.1" value="2"></label><label>Plant response time (ms)<input id="sim-tau" type="number" min="50" max="20000" step="50" value="700"></label></div>
<label class="small" for="sim-curve">Relative valve flow curve, 11 comma-separated values from 0 (closed) to 1 (fully open), increasing and nonlinear:</label><textarea id="sim-curve">0,0.005,0.012,0.025,0.05,0.10,0.19,0.34,0.54,0.78,1</textarea>
<div class="row"><button class="primary" onclick="startSimulation()">Run simulation</button><button onclick="pauseSimulation()">Pause</button><button onclick="resetSimulation()">Reset</button><button onclick="autoTuneSimulation()">Auto-tune simulation</button></div><div id="sim-result" class="small" role="status">Ready. Simulation values are estimates, not a water-test result.</div>
<canvas id="pressure-chart" aria-label="Simulated pressure and supply plot"></canvas><canvas id="actuator-chart" aria-label="Simulated valve position and commands plot"></canvas><div class="small" id="sim-telemetry">Simulation idle.</div>
<details><summary>Controller parameters used in simulation</summary><div class="fields" id="sim-control-fields"></div><div class="row"><button onclick="saveSimulationSettings()">Save simulation settings in this browser</button><button id="apply-candidate" disabled onclick="copyCandidateToController()">Copy candidate to controller form</button></div><p class="small">Auto-tune searches simulation scenarios only. Copying fills the controller form; it does not save or move the real valve.</p></details></section>
<details class="card"><summary>Controller settings and travel limits</summary><p class="small">Saved settings are shared on this ESP. The near-zero clamp sets filtered pressure to zero within the selected ±PSI range; raw pressure remains visible. AUTO requires a user-confirmed pressure-plateau reference after each reboot. A pressure plateau is not proof of a mechanical endstop.</p><div class="fields" id="controller-fields"></div><div class="row"><button class="primary" onclick="saveControllerConfig()">Save controller settings</button></div><div id="config-message" class="small"></div><hr><div>Position reference: <b id="reference-state">unknown</b> · Pulse budget: <span id="reference-budget">--</span></div><div class="row"><button onclick="beginReference('open')">Start bounded OPEN reference</button><button onclick="beginReference('close')">Start bounded CLOSE reference</button><button onclick="markReference()">Mark current position as pressure plateau</button></div><div class="row"><button onclick="showReferenceLog()">Show pressure/pulse log</button><button onclick="clearReferenceLog()">Clear this browser’s log</button></div><canvas id="reference-chart" aria-label="Measured pressure versus cumulative manual pulse time"></canvas><pre id="reference-log" class="small">No reference pulses recorded in this browser.</pre></details>
<details class="card"><summary>Pressure zero and diagnostics</summary><p class="small">Zero only with the sensor pressure port open to atmosphere, MANUAL mode, and the valve stopped. This takes a new 3-second stable sample window and saves a fixed offset once. The adjustable near-zero clamp displays filtered readings inside its ±PSI range as zero; raw readings remain visible.</p><button id="zero-button" onclick="zeroSensor()">Capture 3-second atmospheric zero</button><div class="row"><progress id="zero-progress" max="100" value="0"></progress><span id="zero-state">Idle</span></div><pre id="diag">Loading…</pre></details>
<details class="card"><summary>Wi-Fi settings</summary><p class="small">Changing station Wi-Fi keeps the fallback access point active. The saved password is never returned by the API.</p><div class="fields"><label>Network name (SSID)<input id="wifi-ssid" type="text" maxlength="32" autocomplete="off"></label><label>New Wi-Fi password<input id="wifi-password" type="password" maxlength="63" autocomplete="new-password"></label></div><div class="row"><button class="primary" onclick="saveWifi()">Save and connect</button><span id="wifi-state" class="small">Loading…</span></div></details>
<p class="small">Connection: <span id="wifi">--</span> · Uptime: <span id="uptime">--</span></p></main><script>
const DEFAULT_CONTROL={filterAlpha:.10,zeroClampPsi:.50,deadbandPsi:.75,controlIntervalMs:100,settleMs:400,error1Psi:1.5,error2Psi:3,error3Psi:6,pulse1Ms:70,pulse2Ms:110,pulse3Ms:200,pulse4Ms:325,openTravelMs:4500,closeTravelMs:4500,openOvertravelMs:0,closeOvertravelMs:0};
let currentMode=null,autoBusy=false,controllerConfig={...DEFAULT_CONTROL},latestStatus=null,simTimer=null,sim=null,candidateConfig=null,referenceLog=[];
const $=id=>document.getElementById(id);const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
async function apiGet(path){let r=await fetch(path,{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'Request failed');return j}
async function post(path,body=''){try{let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}),j=await r.json();$('message').textContent=j.error||j.message||'OK';if(!r.ok)throw Error(j.error||'Request failed');await refresh();return j}catch(e){$('message').textContent=e.message;return null}}
function updateAutoToggle(){let b=$('auto-toggle');if(!b)return;const on=currentMode==='auto';b.textContent=currentMode===null?'AUTO: CHECKING…':on?'AUTO: ON · TAP TO TURN OFF':'AUTO: OFF · TAP TO TURN ON';b.setAttribute('aria-pressed',String(on));b.disabled=currentMode===null||autoBusy}
async function toggleAuto(){if(autoBusy||currentMode===null)return;autoBusy=true;updateAutoToggle();await post('/api/auto','enabled='+(currentMode==='auto'?0:1));autoBusy=false;updateAutoToggle()}
function setTarget(){post('/api/setpoint','psi='+encodeURIComponent($('setpoint').value))}
async function zeroSensor(){if(!confirm('Confirm the sensor port is open to atmosphere, the valve is stopped, and AUTO is off. Capture samples for 3 seconds and save one fixed zero offset?'))return;const j=await post('/api/zero','confirmed=1');if(j)$('zero-state').textContent='Collecting fresh samples…'}
function cfgFieldsHtml(c,prefix='cfg'){const labels={filterAlpha:'Pressure filter alpha',zeroClampPsi:'Clamp pressure within ± PSI (0 disables)',deadbandPsi:'Deadband (PSI)',controlIntervalMs:'Control interval (ms)',settleMs:'Settle after pulse (ms)',error1Psi:'Error band 1 (PSI)',error2Psi:'Error band 2 (PSI)',error3Psi:'Error band 3 (PSI)',pulse1Ms:'Pulse 1 (ms)',pulse2Ms:'Pulse 2 (ms)',pulse3Ms:'Pulse 3 (ms)',pulse4Ms:'Pulse 4 (ms)',openTravelMs:'Open travel estimate (ms)',closeTravelMs:'Close travel estimate (ms)',openOvertravelMs:'Open extra budget (ms)',closeOvertravelMs:'Close extra budget (ms)'};return Object.keys(labels).map(k=>`<label>${labels[k]}<input type="number" id="${prefix}-${k}" value="${c[k]}" step="${k==='filterAlpha'||k==='zeroClampPsi'?'0.01':k.includes('Psi')?'0.1':'10'}"></label>`).join('')}
function paintConfig(){ $('controller-fields').innerHTML=cfgFieldsHtml(controllerConfig);$('sim-control-fields').innerHTML=cfgFieldsHtml(controllerConfig,'simcfg') }
function readConfig(prefix){let c={};for(const k of Object.keys(DEFAULT_CONTROL)){c[k]=Number($(`${prefix}-${k}`).value)}return c}
async function loadConfig(){try{controllerConfig={...DEFAULT_CONTROL,...await apiGet('/api/config')};paintConfig()}catch(e){$('config-message').textContent='Could not load settings: '+e.message}}
async function saveControllerConfig(){const c=readConfig('cfg');const body=new URLSearchParams(Object.entries(c));try{let r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}),j=await r.json();$('config-message').textContent=j.message||j.error||'Saved';if(!r.ok)throw Error(j.error||'Save failed');controllerConfig={...c};paintConfig();syncSimControlInputs()}catch(e){$('config-message').textContent=e.message}}
function simController(){return readConfig('simcfg')}
function defaultSim(){return{target:20,supply:60,profile:'step',stepPsi:15,nozzleMm:6,capacityRatio:2,tauMs:700,curve:[0,.005,.012,.025,.05,.1,.19,.34,.54,.78,1],controller:{...DEFAULT_CONTROL}}}
function saveSimulationSettings(){try{localStorage.setItem('pressure-sim-settings',JSON.stringify(readSimForm()));$('sim-result').textContent='Simulation settings saved in this browser.'}catch(e){$('sim-result').textContent='Could not save settings: '+e.message}}
function loadSimulationSettings(){let c=defaultSim();try{const saved=JSON.parse(localStorage.getItem('pressure-sim-settings')||'null');if(saved)c={...c,...saved,controller:{...c.controller,...saved.controller}}}catch{};$('sim-target').value=c.target;$('sim-supply').value=c.supply;$('sim-profile').value=c.profile;$('sim-step').value=c.stepPsi;$('sim-nozzle').value=c.nozzleMm;$('sim-capacity').value=c.capacityRatio;$('sim-tau').value=c.tauMs;$('sim-curve').value=c.curve.join(',');paintConfig();for(const k of Object.keys(c.controller))$(`simcfg-${k}`).value=c.controller[k]}
function syncSimControlInputs(){for(const k of Object.keys(controllerConfig))$(`simcfg-${k}`).value=controllerConfig[k]}
function readSimForm(){const curve=$('sim-curve').value.split(',').map(x=>Number(x.trim())),target=Number($('sim-target').value),supply=Number($('sim-supply').value),stepPsi=Number($('sim-step').value),nozzleMm=Number($('sim-nozzle').value),capacityRatio=Number($('sim-capacity').value),tauMs=Number($('sim-tau').value),controller=simController();if(curve.length!==11||curve.some(x=>!Number.isFinite(x)||x<0||x>1)||curve[0]!==0||curve[10]!==1||curve.some((x,i)=>i&&x<curve[i-1]))throw Error('Valve curve needs 11 increasing values from 0 to 1, starting at 0 and ending at 1');if(!Number.isFinite(target)||target<0||target>120||!Number.isFinite(supply)||supply<0||supply>150||!Number.isFinite(stepPsi)||stepPsi<0||stepPsi>150||!Number.isFinite(nozzleMm)||nozzleMm<.5||nozzleMm>100||!Number.isFinite(capacityRatio)||capacityRatio<.01||capacityRatio>100||!Number.isFinite(tauMs)||tauMs<50||tauMs>20000||!Number.isFinite(controller.zeroClampPsi)||controller.zeroClampPsi<0||controller.zeroClampPsi>5||!Number.isFinite(controller.openTravelMs)||controller.openTravelMs<100||controller.openTravelMs>120000||!Number.isFinite(controller.closeTravelMs)||controller.closeTravelMs<100||controller.closeTravelMs>120000)throw Error('Simulation parameter outside its allowed range');return{target,supply,profile:$('sim-profile').value,stepPsi,nozzleMm,capacityRatio,tauMs,curve,controller}}
function curveAt(pos,curve){const x=clamp(pos,0,100)/10,i=Math.min(9,Math.floor(x)),f=x-i;return curve[i]+(curve[i+1]-curve[i])*f}
function equilibriumPressure(supply,pos,m){const cv=curveAt(pos,m.curve),ratio=m.capacityRatio*Math.pow(6/m.nozzleMm,2)*cv;return supply*(ratio*ratio)/(1+ratio*ratio)}
function sourceAt(t,m,profile=m.profile){if(profile==='hold')return m.supply;if(profile==='step')return t<12?m.supply:t<25?Math.max(0,m.supply-m.stepPsi):m.supply;if(profile==='drop')return t<12?m.supply:Math.max(0,m.supply-m.stepPsi);if(profile==='ramp')return m.supply-m.stepPsi*clamp((t-5)/20,0,1);return m.supply}
function cleanTune(c){c={...c};c.filterAlpha=clamp(c.filterAlpha,.02,.5);c.zeroClampPsi=clamp(Number(c.zeroClampPsi??.5),0,5);c.deadbandPsi=clamp(c.deadbandPsi,.1,10);c.controlIntervalMs=Math.round(clamp(c.controlIntervalMs,50,2000)/10)*10;c.settleMs=Math.round(clamp(c.settleMs,100,5000)/10)*10;c.error1Psi=clamp(c.error1Psi,.2,10);c.error2Psi=clamp(c.error2Psi,c.error1Psi+.1,20);c.error3Psi=clamp(c.error3Psi,c.error2Psi+.1,30);for(let i=1;i<=4;i++)c['pulse'+i+'Ms']=Math.round(clamp(c['pulse'+i+'Ms'],20,1000));for(let i=2;i<=4;i++)c['pulse'+i+'Ms']=Math.max(c['pulse'+(i-1)+'Ms'],c['pulse'+i+'Ms']);return c}
function pulseForError(e,c){const duration=e<=c.error1Psi?c.pulse1Ms:e<=c.error2Psi?c.pulse2Ms:e<=c.error3Psi?c.pulse3Ms:c.pulse4Ms;return e<=c.error1Psi?Math.max(20,Math.round(duration*.65)):duration}
function runEvaluation(m,c,profile){let p=0,f=0,pos=0,pl=0,pdir=0,settle=0,ct=0,pulseTotal=0,maxOver=0,iae=0,prevSign=0,reversals=0;const dt=.05;for(let i=0;i<720;i++){const t=i*dt,supply=sourceAt(t,m,profile),eq=equilibriumPressure(supply,pos,m);p+=(eq-p)*Math.min(1,dt/(m.tauMs/1000));f+=c.filterAlpha*(p-f);if(Math.abs(f)<=c.zeroClampPsi)f=0;const err=m.target-f;iae+=Math.abs(err)*dt;maxOver=Math.max(maxOver,p-m.target);if(pl>0){const used=Math.min(pl,50);pos=clamp(pos+pdir*100*used/(pdir>0?c.openTravelMs:c.closeTravelMs),0,100);pl-=used;if(pl<=0)settle=c.settleMs}else if(settle>0){settle-=50}else{ct+=50;if(ct>=c.controlIntervalMs){ct=0;if(Math.abs(err)>c.deadbandPsi){const sign=err>0?1:-1;if(prevSign&&sign!==prevSign)reversals++;prevSign=sign;pl=pulseForError(Math.abs(err),c);pdir=sign;pulseTotal+=pl}}}}return iae+maxOver*28+(pulseTotal/1000)*.25+reversals*.35}
function scoreTune(m,c){return['hold','drop','step'].reduce((a,p)=>a+runEvaluation(m,c,p),0)}
function autoTuneSimulation(){let m;try{m=readSimForm()}catch(e){$('sim-result').textContent=e.message;return}let best=cleanTune(m.controller),bestScore=scoreTune(m,best),keys=['filterAlpha','deadbandPsi','controlIntervalMs','settleMs','error1Psi','error2Psi','error3Psi','pulse1Ms','pulse2Ms','pulse3Ms','pulse4Ms'];for(let round=0;round<2;round++)for(const key of keys){const base=best[key];for(const factor of [.72,1,1.28]){const trial=cleanTune({...best,[key]:base*factor}),score=scoreTune(m,trial);if(score<bestScore){best=trial;bestScore=score}}}candidateConfig=best;$('apply-candidate').disabled=false;$('sim-result').textContent=`Simulation-only candidate ready. Score ${bestScore.toFixed(1)}; low-overshoot objective. Review before copying.`;}
function copyCandidateToController(){if(!candidateConfig)return;for(const k of Object.keys(candidateConfig))$(`cfg-${k}`).value=candidateConfig[k];$('config-message').textContent='Candidate copied to controller form only. Press Save controller settings to persist it.'}
function resetSimulation(){if(simTimer){clearInterval(simTimer);simTimer=null}const m=readSimForm();sim={running:false,t:0,p:0,f:0,pos:0,pulseLeft:0,pdir:0,settle:0,controlElapsed:0,pulseCount:0,pulseTotal:0,lastCmd:0,data:[],maxPressure:0};$('sim-result').textContent=equilibriumPressure(m.supply,100,m)<m.target?'Target may be unreachable at full opening.':'Simulation reset. No hardware command was sent.';drawSimulation()}
function startSimulation(){let m;try{m=readSimForm()}catch(e){$('sim-result').textContent=e.message;return}if(!sim)resetSimulation();if(simTimer)clearInterval(simTimer);sim.running=true;simTimer=setInterval(simTick,50);$('sim-result').textContent=equilibriumPressure(sourceAt(sim.t,m),100,m)<m.target?'Target unreachable at current supply; simulation running in this browser only.':'Simulation running in this browser only.'}
function pauseSimulation(){if(simTimer)clearInterval(simTimer);simTimer=null;if(sim)sim.running=false;$('sim-result').textContent='Simulation paused. No hardware command was sent.'}
function simTick(){if(!sim||!sim.running)return;let m;try{m=readSimForm()}catch(e){pauseSimulation();$('sim-result').textContent=e.message;return}const c=cleanTune(m.controller),dt=.05,supply=sourceAt(sim.t,m),eq=equilibriumPressure(supply,sim.pos,m),fullOpen=equilibriumPressure(supply,100,m);sim.p+=(eq-sim.p)*Math.min(1,dt/(m.tauMs/1000));sim.f+=c.filterAlpha*(sim.p-sim.f);if(Math.abs(sim.f)<=c.zeroClampPsi)sim.f=0;const err=m.target-sim.f;sim.maxPressure=Math.max(sim.maxPressure,sim.p);sim.lastCmd=0;if(sim.pulseLeft>0){const used=Math.min(50,sim.pulseLeft);sim.pos=clamp(sim.pos+sim.pdir*100*used/(sim.pdir>0?c.openTravelMs:c.closeTravelMs),0,100);sim.pulseLeft-=used;sim.lastCmd=sim.pdir;if(sim.pulseLeft<=0)sim.settle=c.settleMs}else if(sim.settle>0)sim.settle-=50;else{sim.controlElapsed+=50;if(sim.controlElapsed>=c.controlIntervalMs){sim.controlElapsed=0;if(Math.abs(err)>c.deadbandPsi){sim.pdir=err>0?1:-1;sim.pulseLeft=pulseForError(Math.abs(err),c);sim.pulseCount++;sim.pulseTotal+=sim.pulseLeft;sim.lastCmd=sim.pdir}}}sim.t+=dt;if(Math.round(sim.t*4)%1===0){sim.data.push({t:sim.t,p:sim.p,f:sim.f,target:m.target,supply,pos:sim.pos,cmd:sim.lastCmd});if(sim.data.length>420)sim.data.shift()}if(Math.floor(sim.t*2)%2===0)drawSimulation();$('sim-result').textContent=fullOpen<m.target?`UNREACHABLE at current supply (${supply.toFixed(1)} PSI); full-open estimate ${fullOpen.toFixed(1)} PSI.`:'Simulation running in this browser only; no hardware command was sent.';$('sim-telemetry').textContent=`t=${sim.t.toFixed(1)} s · supply=${supply.toFixed(1)} PSI · pressure=${sim.p.toFixed(2)} PSI · filtered=${sim.f.toFixed(2)} PSI · valve=${sim.pos.toFixed(1)}% (estimated) · pulses=${sim.pulseCount} / ${sim.pulseTotal} ms · peak overshoot=${Math.max(0,sim.maxPressure-m.target).toFixed(2)} PSI`;if(sim.t>180)pauseSimulation()}
function drawLine(ctx,data,key,color,min,max){if(data.length<2)return;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();data.forEach((d,i)=>{const x=44+i*(ctx.canvas.width-58)/(data.length-1),y=ctx.canvas.height-20-(clamp((d[key]-min)/(max-min),0,1)*(ctx.canvas.height-34));if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke()}
function drawSimulation(){if(!sim)return;const m=(()=>{try{return readSimForm()}catch{return defaultSim()}})();const data=sim.data.slice(-300);for(const id of ['pressure-chart','actuator-chart']){const cv=$(id),rect=cv.getBoundingClientRect();cv.width=Math.max(320,Math.floor(rect.width*devicePixelRatio));cv.height=Math.floor(190*devicePixelRatio);const x=cv.getContext('2d');x.clearRect(0,0,cv.width,cv.height);x.font=`${12*devicePixelRatio}px system-ui`;x.fillStyle='#a9bbc6';x.fillText(id==='pressure-chart'?'PSI · time':'Position % · pulses',8,16);for(let i=0;i<5;i++){let y=24+i*(cv.height-44)/4;x.strokeStyle='#304550';x.beginPath();x.moveTo(38,y);x.lineTo(cv.width-8,y);x.stroke()}if(id==='pressure-chart'){drawLine(x,data,'supply','#ffbf55',0,Math.max(10,m.supply*1.1));drawLine(x,data,'target','#edf4f7',0,Math.max(10,m.supply*1.1));drawLine(x,data,'p','#47c6a5',0,Math.max(10,m.supply*1.1));drawLine(x,data,'f','#4c9fff',0,Math.max(10,m.supply*1.1))}else{drawLine(x,data,'pos','#47c6a5',0,100);x.strokeStyle='#ffbf55';x.beginPath();data.forEach((d,i)=>{if(d.cmd){let px=44+i*(cv.width-58)/(data.length-1);x.moveTo(px,28);x.lineTo(px,cv.height-18)}});x.stroke()}}}
async function manualPulse(direction){const ms=Number($('manual-ms').value);if(!Number.isInteger(ms)||ms<20||ms>1000)return $('message').textContent='Pulse must be 20–1000 ms';if(!confirm(`Send a ${ms} ms ${direction.toUpperCase()} pulse to the physical valve?`))return;const j=await post('/api/pulse',`direction=${direction}&ms=${ms}`);if(!j)return;await new Promise(r=>setTimeout(r,Math.max(600,Number(controllerConfig.settleMs)+150)));try{const s=await apiGet('/api/status');referenceLog.push({used:s.referencePulseUsedMs||0,pressure:s.pressure,raw:s.rawPressure,direction,time:new Date().toLocaleTimeString()});localStorage.setItem('pressure-reference-log',JSON.stringify(referenceLog));drawReference();showReferenceLog()}catch{}}
async function beginReference(direction){if(!confirm(`Start a bounded ${direction.toUpperCase()} reference session? Each pulse remains manual; stop when pressure plateaus. This does not prove a mechanical endstop.`))return;await post('/api/reference/start','direction='+direction)}async function markReference(){if(!confirm('Confirm the pressure has plateaued in the selected direction. The app will mark an estimated reference, not a mechanical limit.'))return;await post('/api/reference/mark','confirmed=1')}
function drawReference(){const cv=$('reference-chart'),rect=cv.getBoundingClientRect();cv.width=Math.max(320,Math.floor(rect.width*devicePixelRatio));cv.height=180*devicePixelRatio;const x=cv.getContext('2d');x.clearRect(0,0,cv.width,cv.height);x.fillStyle='#a9bbc6';x.fillText('Pressure (PSI) vs cumulative reference pulse time (ms)',8,16);if(referenceLog.length<2)return;const vals=referenceLog.map(v=>Number(v.pressure)).filter(Number.isFinite),hi=Math.max(1,...vals),lo=Math.min(0,...vals),used=referenceLog.map(v=>Number(v.used)||0),umin=Math.min(...used),umax=Math.max(...used);x.strokeStyle='#47c6a5';x.lineWidth=2;x.beginPath();let started=false;referenceLog.forEach((v,i)=>{if(!Number.isFinite(Number(v.pressure)))return;const px=44+(umax>umin?((Number(v.used)-umin)/(umax-umin)):(i/(referenceLog.length-1)))*(cv.width-58),py=cv.height-20-(Number(v.pressure)-lo)/(Math.max(.1,hi-lo))*(cv.height-44);if(started)x.lineTo(px,py);else{x.moveTo(px,py);started=true}});x.stroke()}
function showReferenceLog(){$('reference-log').textContent=referenceLog.length?referenceLog.map((x,i)=>`${i+1}. ${x.time} · ${x.direction} · cumulative ${x.used} ms · pressure ${x.pressure} PSI (raw ${x.raw} PSI)`).join('\n'):'No reference pulses recorded in this browser.';drawReference()}
function clearReferenceLog(){referenceLog=[];localStorage.removeItem('pressure-reference-log');showReferenceLog()}
async function refreshWifi(){try{const s=await apiGet('/api/wifi');$('wifi-ssid').value=s.ssid||'';$('wifi-state').textContent=`${s.state}${s.ip?' · '+s.ip:''}${s.error?' · '+s.error:''}`}catch(e){$('wifi-state').textContent='Wi-Fi status unavailable: '+e.message}}
async function saveWifi(){const ssid=$('wifi-ssid').value.trim(),password=$('wifi-password').value;if(!ssid||ssid.length>32||password.length>63)return $('wifi-state').textContent='SSID must be 1–32 characters; password 0–63.';const j=await post('/api/wifi',new URLSearchParams({ssid,password}).toString());$('wifi-password').value='';if(j){$('wifi-state').textContent='Connection change requested. Fallback AP stays available.';setTimeout(refreshWifi,1000)}}
async function refresh(){try{const s=await apiGet('/api/status');latestStatus=s;currentMode=s.mode;updateAutoToggle();$('pressure').textContent=s.pressure===null?'--':Number(s.pressure).toFixed(2);$('raw-pressure').textContent=Number(s.rawPressure).toFixed(2);$('pressure-clamp').textContent=Number(s.zeroClampPsi).toFixed(2);$('target').textContent=Number(s.target).toFixed(1);$('setpoint').value=s.target;$('mode').textContent=s.mode;$('valve').textContent=s.valve;$('position').textContent=s.positionKnown?`${Number(s.valvePosition).toFixed(1)}% estimated`:'unknown — reference required';$('reference-state').textContent=s.positionKnown?'estimated reference set':s.referenceActive?`${s.referenceDirection} reference active`:'unknown';$('reference-budget').textContent=s.referenceActive?`${s.referencePulseUsedMs}/${s.referencePulseBudgetMs} ms`:'—';const f=$('fault');f.textContent=s.system.toUpperCase();f.className='value fault'+(s.fault==='sensor'?' bad':s.fault==='overpressure'?' warn':'');$('wifi').textContent=s.wifi+' · '+s.ip;$('uptime').textContent=Math.floor(s.uptimeMs/1000)+' s';$('notice').textContent=s.warning;$('zero-progress').value=s.zeroCaptureProgress||0;$('zero-state').textContent=s.zeroCaptureActive?`Collecting ${s.zeroCaptureSamples}/60 (${s.zeroCaptureProgress}%)`:s.zeroCaptureError||s.lastAction;$('zero-button').disabled=s.zeroCaptureActive;$('diag').textContent=`ADC: ${s.adcMillivolts} mV (${s.adcVoltage.toFixed(3)} V)\nSensor: ${s.sensorVoltage.toFixed(3)} V\nRaw pressure: ${s.rawPressure.toFixed(3)} PSI\nZero offset (fixed): ${s.pressureOffsetPsi.toFixed(3)} PSI\nFiltered pressure: ${s.pressure===null?'invalid':s.pressure.toFixed(3)+' PSI'}\nFilter alpha: ${s.filterAlpha}\nZero clamp: ±${Number(s.zeroClampPsi).toFixed(2)} PSI\nLast action: ${s.lastAction}\nPosition reference: ${s.positionKnown?'estimated':'unknown'}\nWi-Fi RSSI: ${s.wifiRssi} dBm\nLast error: ${s.lastError||'none'}`}catch(e){$('message').textContent='Status unavailable'}}
function init(){try{referenceLog=JSON.parse(localStorage.getItem('pressure-reference-log')||'[]')}catch{referenceLog=[]}loadSimulationSettings();loadConfig().then(()=>{syncSimControlInputs();resetSimulation()});showReferenceLog();refresh();refreshWifi();setInterval(refresh,500);setInterval(refreshWifi,3000)}init();
</script></body></html>
)UI";
